In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import string
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import re
from sklearn.cross_validation import train_test_split
%matplotlib inline
eng_stopwords = set(stopwords.words("english"))

In [2]:
train=pd.read_csv(r'C:\Users\d.ak.kumar\Documents\hackathon\twitter\train.csv', encoding='latin-1')

In [3]:
train.head(4)

Sentiment                                      SentimentText
0          0                       is so sad for my APL frie...
1          0                     I missed the New Moon trail...
2          1                            omg its already 7:30 :O
3          0            .. Omgaga. Im sooo  im gunna CRy. I'...

In [4]:
train.Sentiment.value_counts()

1    56457
0    43532
Name: Sentiment, dtype: int64

In [5]:
train.SentimentText[3]

"          .. Omgaga. Im sooo  im gunna CRy. I've been at this dentist since 11.. I was suposed 2 just get a crown put on (30mins)..."

In [6]:
df5=train.rename(columns={'SentimentText':'body','Sentiment':'label'})[0:50000]

In [7]:
def removePunctuation(x):
    # Lowercasing all words
    x = x.lower()
    # Removing non ASCII chars
    x = re.sub(r'[^\x00-\x7f]',r' ',x)
    # Removing (replacing with empty spaces actually) all the punctuations
    return re.sub("["+string.punctuation+"]", " ", x)

In [8]:
df5["body"] = df5["body"].map(removePunctuation)

In [9]:
df5.head(4)

label                                               body
0      0                       is so sad for my apl frie...
1      0                     i missed the new moon trail...
2      1                            omg its already 7 30  o
3      0               omgaga  im sooo  im gunna cry  i ...

In [10]:
def removeStopwords(x):
    # Removing all the stopwords
    filtered_words = [word for word in x.split() if word not in eng_stopwords]
    return " ".join(filtered_words)

In [11]:
df5["body"] = df5["body"].map(removeStopwords)

In [12]:
df5.head(4)

label                                               body
0      0                                     sad apl friend
1      0                            missed new moon trailer
2      1                                   omg already 7 30
3      0  omgaga im sooo im gunna cry dentist since 11 s...

In [13]:
df5['body'][3]

'omgaga im sooo im gunna cry dentist since 11 suposed 2 get crown put 30mins'

In [14]:
tfidf_vectorizer = TfidfVectorizer(use_idf=True, ngram_range=(1,1))  
tfidf_matrix = tfidf_vectorizer.fit_transform(df5['body'])
feature_names = tfidf_vectorizer.get_feature_names() 

In [15]:
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix , df5['label'], test_size=0.5, random_state=42)

In [16]:
from sklearn.naive_bayes import MultinomialNB

In [17]:
nb = MultinomialNB(class_prior=None, alpha=1, fit_prior=True,)

In [18]:
nb.fit(X_train,y_train)

MultinomialNB(alpha=1, class_prior=None, fit_prior=True)

In [19]:
pred=nb.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix

In [21]:
confusion_matrix(y_test, pred)

array([[ 7064,  4531],
       [ 2301, 11104]])

In [22]:
(7064+11104)/X_test.shape[0]

0.72672

In [24]:
print((7064+11104)/(7064+4531+2301+11104))
print((7064)/(7064+4531))
print((11104)/(11104+2301))

0.72672
0.6092281155670548
0.8283476314807907


In [25]:
print(tfidf_matrix)

  (0, 29455)	0.44397709967
  (0, 16159)	0.815057356221
  (0, 47486)	0.372244329759
  (1, 53656)	0.592125973475
  (1, 40023)	0.563824985445
  (1, 41148)	0.365452198048
  (1, 39616)	0.444896514108
  (2, 1393)	0.644389973625
  (2, 11057)	0.526490896651
  (2, 42273)	0.554588944746
  (3, 1424)	0.34228520648
  (3, 45236)	0.201195550186
  (3, 24105)	0.319545575809
  (3, 30120)	0.131802439486
  (3, 51534)	0.365024837151
  (3, 245)	0.248386835737
  (3, 49185)	0.205847422452
  (3, 25179)	0.280878204639
  (3, 24152)	0.22495163797
  (3, 31150)	0.286358639811
  (3, 49983)	0.224723021349
  (3, 33301)	0.30054446057
  (3, 42274)	0.365024837151
  (4, 22143)	0.590983024502
  (4, 19510)	0.516363508619
  :	:
  (49995, 40360)	0.25580528312
  (49996, 17943)	0.579685379944
  (49996, 55336)	0.514417909022
  (49996, 30334)	0.403362644791
  (49996, 46040)	0.375355201673
  (49996, 18319)	0.309428706686
  (49997, 17944)	0.805999056961
  (49997, 30563)	0.494692338452
  (49997, 36019)	0.325030783859
  (49998, 47825

In [26]:
for i, feature in enumerate(tfidf_vectorizer.get_feature_names()):
    print(i, feature)

0 00
1 000
2 0001t
3 000martha
4 001
5 0010x0010
6 0022
7 007
8 007heather007
9 007hil
10 007jbond
11 007louiseob
12 007peter
13 00a
14 00am
15 00fieldsy
16 00geneva
17 00h
18 00k
19 00mathias
20 00mony00
21 00neji
22 00pet00
23 00pm
24 00ps
25 00seve
26 00vicky00
27 01
28 01000101
29 011
30 011iver
31 012
32 016578
33 017
34 01jamcon
35 01movie
36 01ps
37 01theone
38 02
39 0205laura
40 021
41 0239
42 02plane
43 02sweetpea02
44 03
45 0309love
46 03l
47 03robin
48 04
49 0411247113
50 0433963407
51 0448417513
52 04pm
53 04youenc
54 05
55 0517
56 05jstone
57 05pm
58 06
59 061004
60 06atmfj
61 06eleven
62 06falloutgirl06
63 07
64 0700
65 071
66 0716
67 07am
68 07nick07
69 07thking
70 07yez
71 08
72 0811thereason
73 087r9
74 08erica09
75 08fjw
76 08sikid
77 08zlk
78 09
79 09011
80 090595
81 093m3
82 094459
83 09aoc
84 09casper
85 09ch
86 09mileycyrusfan
87 0amityville0
88 0boy
89 0bscenity
90 0bxmudm0mma
91 0chick
92 0cl0ver
93 0colleen
94 0dds0cksmyelb0w
95 0dpg9z
96 0e7bethany
97 0f
98 0h

In [27]:
from nltk.stem.wordnet import WordNetLemmatizer
from nltk import SnowballStemmer

In [28]:
#nltk.download()

In [29]:
lmt = WordNetLemmatizer()
stemmer = SnowballStemmer("english")


In [41]:
train=pd.read_csv(r'C:\Users\d.ak.kumar\Documents\hackathon\twitter\train.csv', encoding='latin-1')

In [42]:
df5=train.rename(columns={'SentimentText':'body','Sentiment':'label'})[0:50000]

In [43]:
def removePunctuation1(x):
    # Lowercasing all words
    x = x.lower()
    # Removing non ASCII chars
    x = re.sub(r'[^\x00-\x7f]',r' ',x)
    word=lmt.lemmatize(x)
    #word = stemmer.stem(x)
    # Removing (replacing with empty spaces actually) all the punctuations
    return re.sub("["+string.punctuation+"]", " ", word)

In [44]:
df5["body"] = df5["body"].map(removePunctuation1)

In [45]:
tfidf_vectorizer = TfidfVectorizer(use_idf=True, ngram_range=(1,1))  
tfidf_matrix = tfidf_vectorizer.fit_transform(df5['body'])
feature_names = tfidf_vectorizer.get_feature_names() 

In [46]:
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix , df5['label'], test_size=0.5, random_state=42)

In [47]:
nb.fit(X_train,y_train)

MultinomialNB(alpha=1, class_prior=None, fit_prior=True)

In [48]:
pred=nb.predict(X_test)

In [49]:
confusion_matrix(y_test, pred)

array([[ 7158,  4437],
       [ 2125, 11280]])

In [51]:
print((7158+11280)/(7158+11280+2125+4437))
print((7158)/(7158+4437))
print((11280)/(11280+2125))

0.73752
0.6173350582147478
0.8414770607982096


In [40]:
confusion_matrix(y_test, pred)

array([[ 7122,  4473],
       [ 2113, 11292]])

In [112]:
print((7122+11292)/(7122+11292+2113+4473))
print((7122)/(7122+4473))
print((11292)/(11292+2113))

0.73656
0.6142302716688227
0.8423722491607609


In [113]:
for i, feature in enumerate(tfidf_vectorizer.get_feature_names()):
    print(i, feature)

0 00
1 000
2 0001t
3 000martha
4 001
5 0010x0010
6 0022
7 007
8 007heather007
9 007hil
10 007jbond
11 007louiseob
12 007peter
13 00a
14 00am
15 00fieldsy
16 00geneva
17 00h
18 00k
19 00mathias
20 00mony00
21 00neji
22 00pet00
23 00pm
24 00ps
25 00seve
26 00vicky00
27 01
28 01000101
29 011
30 011iver
31 012
32 016578
33 017
34 01jamcon
35 01movie
36 01ps
37 01theone
38 02
39 0205laura
40 021
41 0239
42 02plane
43 02sweetpea02
44 03
45 0309love
46 03l
47 03robin
48 04
49 0411247113
50 0433963407
51 0448417513
52 04pm
53 04youenc
54 05
55 0517
56 05jstone
57 05pm
58 06
59 061004
60 06atmfj
61 06eleven
62 06falloutgirl06
63 07
64 0700
65 071
66 0716
67 07am
68 07nick07
69 07thking
70 07yez
71 08
72 0811thereason
73 087r9
74 08erica09
75 08fjw
76 08sikid
77 08zlk
78 09
79 09011
80 090595
81 093m3
82 094459
83 09aoc
84 09casper
85 09ch
86 09mileycyrusfan
87 0amityville0
88 0boy
89 0bscenity
90 0bxmudm0mma
91 0chick
92 0cl0ver
93 0colleen
94 0dds0cksmyelb0w
95 0dpg9z
96 0e7bethany
97 0f
98 0h

In [114]:
df6=df5[['body']][0:20]

In [115]:
tfidf_vectorizer = TfidfVectorizer(use_idf=True, ngram_range=(1,1),stop_words= 'english')  
tfidf_matrix = tfidf_vectorizer.fit_transform(df6['body'])
#tfidf_matrix_test = tfidf_vectorizer.fit_transform(X_test)
feature_names = tfidf_vectorizer.get_feature_names() #

In [116]:
df1 = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)

In [119]:
print(df1[0:2])

   102   11  112  27hx   30  30mins  alreadi      apl  australia  awhhe  ...   \
0  0.0  0.0  0.0   0.0  0.0     0.0      0.0  0.57735        0.0    0.0  ...    
1  0.0  0.0  0.0   0.0  0.0     0.0      0.0  0.00000        0.0    0.0  ...    

   uniform  useless   ve  way  weekend  win  wonder  work  worry  year  
0      0.0      0.0  0.0  0.0      0.0  0.0     0.0   0.0    0.0   0.0  
1      0.0      0.0  0.0  0.0      0.0  0.0     0.0   0.0    0.0   0.0  

[2 rows x 90 columns]


In [120]:
df1.head(3)

102   11  112  27hx        30  30mins  alreadi      apl  australia  awhhe  \
0  0.0  0.0  0.0   0.0  0.000000     0.0      0.0  0.57735        0.0    0.0   
1  0.0  0.0  0.0   0.0  0.000000     0.0      0.0  0.00000        0.0    0.0   
2  0.0  0.0  0.0   0.0  0.707107     0.0      0.0  0.00000        0.0    0.0   

   ...   uniform  useless   ve  way  weekend  win  wonder  work  worry  year  
0  ...       0.0      0.0  0.0  0.0      0.0  0.0     0.0   0.0    0.0   0.0  
1  ...       0.0      0.0  0.0  0.0      0.0  0.0     0.0   0.0    0.0   0.0  
2  ...       0.0      0.0  0.0  0.0      0.0  0.0     0.0   0.0    0.0   0.0  

[3 rows x 90 columns]